### ISSUE TITLE
Add SEO meta tags for posts

### ISSUE THREAD

**Issue by katatsu12** [activebridge/activebridge.github.io#101]

**Comment by Smoke-ck** [comment]
@katatsu12 , Thanks, I will switch here after 'Navbar' task.

**Comment by Smoke-ck** [comment]
@katatsu12,
This is finished for now. 
  - Added SEO meta tags
  - Included missing posts
  - Fixed links between posts and other pages

Current updates are saved in the [feature/add_posts](https://github.com/katatsu12/live_blog/tree/feature/add_posts) branch, pending deployment.
Any additional changes will be added as needed.
