### ISSUE TITLE
Clean up CSS

### ISSUE THREAD

**Issue by katatsu12** [activebridge/activebridge.github.io#104]
Remove extra CSS

**Comment by Smoke-ck** [comment]
@katatsu12, I will take styles that belongs to carousel, because I'm going to add some fixes to it.

**Comment by katatsu12** [comment]
> @katatsu12, I will take styles that belongs to carousel, because I'm goin to add some fixes to it.

Ok, we could split this task by few PRs

**Comment by Smoke-ck** [comment]
@katatsu12 , in this pr #111 I removed unused styles which belongs to carousel, and add some fixes as well.

**Comment by KateNaumenko** [comment]
@katatsu12 in this pr https://github.com/katatsu12/live_blog/pull/128 I've removed unused styles and add some fixes as well
