### ISSUE TITLE
Add cursor pointer to buttons + typo

### ISSUE THREAD

**Issue by jawny-utah** [activebridge/activebridge.github.io#138]
Send button don't have a `cursor: pointer` attribute on this page
https://activebridge.org/contacts
<img width="875" alt="image" src="https://github.com/activebridge/activebridge.github.io/assets/59439383/f2237b16-1703-4c5a-b1f0-2e04af3c1483">

Add it

---

Fix typo at the bottom of this page
https://activebridge.org/services/mobile-app-development
<img width="665" alt="image" src="https://github.com/activebridge/activebridge.github.io/assets/59439383/35a2ffa6-5131-440f-9af4-8c47479e6ba1">

I believe it should be `proJect`

**Comment by Smoke-ck** [comment]
@jawny-utah, Thank you for your help and support!

**Comment by Smoke-ck** [comment]
#139
