### ISSUE TITLE
Horizontal scroll issue

### ISSUE THREAD

**Issue by katatsu12** [activebridge/activebridge.github.io#141]
We have a horizontal scroll on some pages:

Blog show page:
![image](https://github.com/activebridge/activebridge.github.io/assets/22080708/aa6233f2-100d-48fa-a5be-14cfdb8032cc)

Check the root page section:
![image](https://github.com/activebridge/activebridge.github.io/assets/22080708/910e082b-cd85-4609-a6e0-565070c3774f)

**Comment by Smoke-ck** [comment]
#147
