### ISSUE TITLE
Blog updates

### ISSUE THREAD

**Issue by katatsu12** [activebridge/activebridge.github.io#145]
Issue checklist:

- [x] Add spacing for images + text (line-height)
- [x] Check font styles
- [x] update background gradient

Current state:
![image](https://github.com/activebridge/activebridge.github.io/assets/22080708/756c97d9-3fbc-4b3c-b3b5-8854ad255c6f)

Origin design example:
![BLOG_Post](https://github.com/activebridge/activebridge.github.io/assets/22080708/d16db2b3-78ca-4ee1-8a15-4d77cff8021a)

**Comment by Smoke-ck** [comment]
#149
