### ISSUE TITLE
Website Content and Layout Corrections

### ISSUE THREAD

**Issue by daryakuritsyna** [activebridge/activebridge.github.io#150]
This ticket consolidates various corrections and improvements needed across our website, from typo fixes to layout adjustments. Tasks are grouped by page for efficient tracking and implementation. The blog section is not considered.

# Tasks:

## General:

**Button Text Update:** 
Replace text on "see our services" button with "Learn more about our services" across all applicable pages.

**Uniform Subtitles Font:**
Ensure the font size for subtitles is consistent across all sections.

## [Homepage](https://activebridge.org/):

**Text Correction**: 
In h2 subtitle, change "cloud-base engineering" to "cloud-based engineering".

## About Page:

**Text Visibility:** Adjust the text describing Active Bridge’s approach to ensure it is readable against the background.

**Key Facts Section Adjustments**:
- Reduce the spacing between words and letters.
- Insert "the" before "team of dedicated Ruby on Rails developers".

## Team Page:

**Missing Elements:**
- Add the subheader "Crew".
- Include the missing description for "Mobile application development services" under the "Build a great product with our Ruby on Rails expertise" section.

## Expertise Page:

**Missing title=h1 tag**: Add "Ruby on Rails custom development solutions" as the H1 tag.

## Services Page:

**Text Visibility:** Ensure the text in the "Custom Ruby on Rails development services" block is visible against the background.

**Title Correction:** Remove the dot after the sentence in the title.

## Web Development Service Page:

**Text Formatting:** Ensure the "full-stack web development services" section's paragraphs are visually separated as per the mockup.

## RoR Development Page:

**Content Adjustments:**
- Remove dots in titles within the "Our Ruby on Rails development approach" section.
- Correct the spelling mistake in "Infrastructure" and adjust the phrase to "the cost-effective and rapid development of MVPs".
- Add the specified text to the paragraph titled "Release". 
`We handle all technical aspects of deployment, including configuration, setup, and distribution to app stores or other platforms.`

## Mobile App Development Page:

**Deployment and Support Text Addition:** Add detailed deployment and support information in the "Cross-platform application development approach" section. 
`Our team handles the technical aspects of deployment, configuration, setup, and distribution to app stores or other platforms during the Deployment & Support stage. We ensure a seamless launch and provide ongoing support to address post-launch issues.Output: Deployed application across desired platforms Ongoing support and maintenance services Continuous monitoring and updates for optimal performance`

## Solution Page:

**Duplicate Badges:** Replace duplicated badges in the first section.
**Missing Content Block:** Add the specified missing content block, referencing the provided Google Doc for details.

## InsurTech/Cloud Software Page:

**List Alignment**: Ensure the list in "Insurance product design and development" is left-aligned.

## Taxi and Transportation Page:

**Font Style Consistency:** The font style in the "Challenge" paragraph should match the rest of the page's text style.

## Review Page:

**Missing Content Block:** Verify and add the missing content block as per the Google Doc.

## Contact Page:

**Button Placement:** Adjust the placement of the "send" button and related text blocks for clarity and user experience. The button "send" should be placed above the text block "After the form submission" and above the button "learn more how we process the data"

**Comment by Smoke-ck** [comment]
#152

**Comment by Smoke-ck** [comment]
#153

**Comment by Smoke-ck** [comment]
Hi @daryakuritsyna,  it's already in prod.

**Comment by Smoke-ck** [comment]
![Screenshot from 2024-04-16 12-42-05](https://github.com/activebridge/activebridge.github.io/assets/72155871/8c9764f2-3307-415d-88a7-dfb938af41af)
Check letter-spacing.
Fixed #183

**Comment by Smoke-ck** [comment]
> ![Screenshot from 2024-04-16 12-42-05](https://private-user-images.githubusercontent.com/72155871/322792476-8c9764f2-3307-415d-88a7-dfb938af41af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzEyMDcsIm5iZiI6MTcxMzI3MDkwNywicGF0aCI6Ii83MjE1NTg3MS8zMjI3OTI0NzYtOGM5NzY0ZjItMzMwNy00MTVkLTg4YTctZGZiOTM4YWY0MWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDEyMzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYTlhYTVlODViNjNhYTk1ODc5Y2JlMjRhZWQ5MmE3ODA5MDkxMTlmZTFmYzA0ZjZhMjRlZDA4Nzk0NzRmNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QvY_G42-SgKRcmX5mOSsNYWkl_KmmVoiOlqA0wgQ5Sg) Check letter-spacing

#183

**Comment by daryakuritsyna** [comment]
content folder https://drive.google.com/drive/folders/1fKVEWi4yZKdwm_25zLXGTBEtAfzR-XwK?usp=drive_link
font size optimization instructions https://www.figma.com/file/zW3ch0tAnTnEPsdaRJECjx/Active-Bridge-Website?type=design&node-id=4289%3A2&mode=design&t=T564vzZFzqxefDmt-1

**Comment by Smoke-ck** [comment]
> content folder https://drive.google.com/drive/folders/1fKVEWi4yZKdwm_25zLXGTBEtAfzR-XwK?usp=drive_link font size optimization instructions https://www.figma.com/file/zW3ch0tAnTnEPsdaRJECjx/Active-Bridge-Website?type=design&node-id=4289%3A2&mode=design&t=T564vzZFzqxefDmt-1

@daryakuritsyna,  I'll be doing this in parts so we can test all the changes and make sure we don't miss any mistakes

**Comment by Smoke-ck** [comment]
#189 - Home Page
#195 - About Us
#196 - Team
#197 - Expertise
#199 - Services
#200 - Services/Web-dev
#201 - Services/Ror-dev
#202 - Services/Mob-dev
#203 - Services/Dedicted teams
#204 - Services/Project-dev
#205 - Solutions
#206 - Solutions/Healthcare Hipaa Case
#207 - Solutions/Insurtech
#208 - Solutions/Marketplace
#209 - Solutions/Ecommerce
#210 - Solutions/Taxi and Transportation
#212 - Reviews
#213 - FAQ
#214 - Privacy Policy
#215 - Blog
#216 - Contact Us and 404
