### ISSUE TITLE
 Corrections to linking issues across some pages

### ISSUE THREAD

**Issue by daryakuritsyna** [activebridge/activebridge.github.io#151]
There are incorrect and outdated links across several pages and sections of our website, particularly within "Engagement Models" blocks and policy references. 

Tasks:
**Engagement Models and Contract Type Link Corrections:**

1. Services Page - Engagement Models Block:

Update the link for "Project Outsourcing (+Workflow)" to point to [Project Development Cooperation](https://activebridge.org/services/project-development-cooperation).
Update the link for "Staff Augmentation (+Workflow)" to point to [Dedicated Teams Cooperation](https://activebridge.org/services/dedicated-teams-cooperation).

2. Web Development Page - Partnership Contract Approaches Block:

Update the "Team extension contract type" link to [Dedicated Teams Cooperation](https://activebridge.org/services/dedicated-teams-cooperation).
Update the "Project outsourcing contract type" link to [Project Development Cooperation](https://activebridge.org/services/project-development-cooperation).

3. RoR Development Page - Engagement Models Block:

Ensure the "Staff Augmentation (+Workflow)" link directs to [Dedicated Teams Cooperation](https://activebridge.org/services/dedicated-teams-cooperation).
Correct the link for the ticket that should direct to [Project Development Cooperation](https://activebridge.org/services/project-development-cooperation).

4. Mobile App Development Page - Engagement Models Block:
Ensure the "Staff Augmentation (+Workflow)" link directs to [Dedicated Teams Cooperation](https://activebridge.org/services/dedicated-teams-cooperation).
Correct the link for the ticket that should direct to [Project Development Cooperation](https://activebridge.org/services/project-development-cooperation).

5. Contact Us Page:
The button "learn more how we process your data" should link to the [Privacy Policy](https://activebridge.org/privacy_policy) page.

6. Privacy Policy Page:
Update the last sentence from "This Privacy Policy was last updated on June 20, 2021" to "This Privacy Policy was last updated on March 20, 2024".

**Comment by Smoke-ck** [comment]
#154

**Comment by Smoke-ck** [comment]
Hi @daryakuritsyna, it's already in prod.
