### ISSUE TITLE
SEO. Resolution of 404 status code

### ISSUE THREAD

**Issue by daryakuritsyna** [activebridge/activebridge.github.io#163]
5 critical pages are returning a 404 status code, indicating that these pages are not found.

Blog Insights Category: https://activebridge.org/blog/category/insights
Contact: https://activebridge.org/contact
How We Work: https://activebridge.org/how-we-work
Portfolio: https://activebridge.org/portfolio
Team: https://activebridge.org/team

Suggested action:  implement 301 redirects from the old URL to the new URL to preserve SEO value and guide users to the correct content.
https://activebridge.org/contact -> https://activebridge.org/contacts
https://activebridge.org/how-we-work -> https://activebridge.org/expertise
https://activebridge.org/portfolio -> https://activebridge.org/solutions
https://activebridge.org/team -> https://activebridge.org/about/team
https://activebridge.org/blog/category/insights -> https://activebridge.org/blog/inside_ab/

**Comment by Smoke-ck** [comment]
#176

**Comment by Smoke-ck** [comment]
Hi @daryakuritsyna, it's already in prod.
