### ISSUE TITLE
SEO. Resolve duplicate meta issues with canonical tags or 301

### ISSUE THREAD

**Issue by daryakuritsyna** [activebridge/activebridge.github.io#164]
25 of our website's pages are serving duplicate meta descriptions. This is not optimal for search engine rankings as it can cause search engine algorithms to struggle with page differentiation and authority. The affected pages include various iterations of our homepage, blog pages, and some service-related pages. The usage of rel="canonical" links is a recommended approach to solve this.

For Links:
https://activebridge.org
https://activebridge.org/
https://activebridge.org/contacts
https://activebridge.org/contacts.html
https://activebridge.org/index
https://activebridge.org/reviews
https://activebridge.org/reviews.html
https://activebridge.org/services
https://activebridge.org/services.html

Solution: implement 301 redirects for any URLs that are no longer needed, directing them to the relevant canonical pages.

For Links:
https://activebridge.org/blog/
https://activebridge.org/blog//
https://activebridge.org/blog/2/
https://activebridge.org/blog/3/
https://activebridge.org/blog/4/
https://activebridge.org/blog/5/
https://activebridge.org/blog/6/
https://activebridge.org/blog/7/
https://activebridge.org/blog/business_growth/
https://activebridge.org/blog/engineering/
https://activebridge.org/blog/engineering/2/
https://activebridge.org/blog/engineering/3/
https://activebridge.org/blog/engineering/4/
https://activebridge.org/blog/inside_ab/
https://activebridge.org/blog/pm_team_management/
https://activebridge.org/blog/pm_team_management/2/

Solution: Implement rel="canonical" tags on the header of each page, pointing to the determined canonical URL. This will indicate to search engines which page is the preferred one when multiple pages contain identical or very similar content.
Example: ink rel="canonical" href="https://activebridge.org/blog/"  should be placed on all duplicate or similar blog pages' headers.

**Comment by Smoke-ck** [comment]
#175

**Comment by Smoke-ck** [comment]
Hi @daryakuritsyna, it's already in prod.
