### ISSUE TITLE
Resolve issue with duplication and search indexing of paginated pages

### ISSUE THREAD

**Issue by daryakuritsyna** [activebridge/activebridge.github.io#177]
We need to enhance our SEO strategy for the paginated pages of our blog by implementing unique meta tags for each page and utilizing canonical tags to manage duplicate content issues effectively.

Using both unique meta tags and canonical tags allows for a nuanced approach. Unique meta tags improve user experience and search matching for each page's specific content. At the same time, canonical tags ensure that search engines correctly understand and index the structure of AB site, particularly when dealing with paginated series or similar content spread across multiple URLs.

## Solution.

**1. Unique Meta Tags.**
Resource: All the meta tags are documented and available in the following Google Docs spreadsheet: [SEO Meta Tags Sheet](https://docs.google.com/spreadsheets/d/13yzTg37dof-sfYPnn26rmYTDV2N2pUNIEUl80vEnRmw/edit?usp=sharing).

For paginated content, like a blog series, it's beneficial to indicate the page number or series part within the title and meta description for each paginated page. 

- Title Tag example for page 1: "Latest Blog Posts | ActiveBridge Blog"

- Title Tag example for page 2: "Latest Blog Posts - Page 2 | ActiveBridge Blog"

**2. Meta Tags for Pagination.**
Use the rel="next" and rel="prev" links to indicate the relationship between paginated pages. 
F ex. for link https://activebridge.org/blog/2/

```
<link rel="prev" href="https://activebridge.org/blog/" />
<link rel="next" href="https://activebridge.org/blog/3/" />
```

**3. Canonical Tags.**
 Use canonical tags on each paginated page to inform search engines that while each page is part of a larger sequence, it should be considered for indexing as its own entity.
 

- Implement a self-referencing canonical tag on each paginated blog page. This indicates to search engines that each page, although part of a sequence, is distinct and valuable.

_blog series 1:_

- Example for page 1: link rel="canonical" href="https://activebridge.org/blog/"

- Example for page 2: link rel="canonical" href="https://activebridge.org/blog/2/"

_blog series 2:_

- Example for page 1: link rel="canonical" href="https://activebridge.org/blog/engineering"

- Example for page 2: link rel="canonical" href="https://activebridge.org/blog/engineering/2/"

**Comment by Smoke-ck** [comment]
#180

**Comment by Smoke-ck** [comment]
Hi @daryakuritsyna, it's already in prod.
