### ISSUE TITLE
🔴 Google Tag Manager script not detected on website

### ISSUE THREAD

**Issue by daryakuritsyna** [activebridge/activebridge.github.io#184]
Google Tag Manager (GTM) script is no longer detected on our website. This script is crucial for gathering analytical data and configuring settings for our analytical tools.

![GTM test](https://prnt.sc/DGYSMmtDYork)

**Comment by Smoke-ck** [comment]
#190

**Comment by Smoke-ck** [comment]
Hi @daryakuritsyna, it's already in prod.
