### ISSUE TITLE
Standardize Margins and Paddings Across All Pages

### ISSUE THREAD

**Issue by Smoke-ck** [activebridge/activebridge.github.io#188]
To improve the consistency and visual appeal of our website, we need to standardize the margins and paddings used across all pages. This task involves defining a set of standard margin and padding values and applying these consistently within our CSS.

**Comment by Smoke-ck** [comment]
I will switch here after urgent tasks.

**Comment by daryakuritsyna** [comment]
there are some elements to improve 

**left alignment:**

![Screenshot_2024-04-29-22-33-14-127_com.android.chrome-edit.jpg](https://github.com/activebridge/activebridge.github.io/assets/12555828/3378d65c-13f7-4ad3-86b3-99eb604f0353)

![Screenshot_2024-04-29-22-28-34-768_com.android.chrome-edit.jpg](https://github.com/activebridge/activebridge.github.io/assets/12555828/93434dac-d73b-413a-9525-ae35d8a2f342)

![IMG_20240429_124422_952.jpg](https://github.com/activebridge/activebridge.github.io/assets/12555828/d4177791-4a83-45fd-8dcc-da45ed110e23)

**space unification between words in some paragraphs**

![Screenshot_2024-04-29-22-32-20-534_com.android.chrome-edit.jpg](https://github.com/activebridge/activebridge.github.io/assets/12555828/7a8c2ab6-e210-4841-91df-ac25d143f2bf)

![Screenshot_2024-04-29-22-31-11-198_com.android.chrome-edit.jpg](https://github.com/activebridge/activebridge.github.io/assets/12555828/ccfed97b-69a5-4998-99c6-b663ffe4fce1)

![Screenshot_2024-04-29-22-30-04-666_com.android.chrome-edit.jpg](https://github.com/activebridge/activebridge.github.io/assets/12555828/11ef766e-0db4-4cb3-b4fa-02092421d466)

![Screenshot_2024-04-29-22-29-14-176_com.android.chrome-edit.jpg](https://github.com/activebridge/activebridge.github.io/assets/12555828/f8dbc4d9-0c8e-40b1-8329-aad2bbd0f695)

![Screenshot_2024-04-29-22-28-14-068_com.android.chrome-edit.jpg](https://github.com/activebridge/activebridge.github.io/assets/12555828/22db134f-6a90-41b4-9a1b-e2825a7ba1ee)

![Screenshot_2024-04-29-22-24-18-880_com.android.chrome-edit.jpg](https://github.![IMG_20240429_122049_762.jpg](https://github.com/activebridge/activebridge.github.io/assets/12555828/cdebbc0e-245f-4c8f-8f9b-968e9be52338)/12555828/68f45754-62be-4521-90d6-a72a1577f69e)

![IMG_20240429_122049_363.jpg](https://github.com/activebridge/activebridge.github.io/assets/12555828/ab1def99-178f-46d8-91c8-38ca3803976b)

![IMG_20240429_122049_428.jpg](https://github.com/activebridge/activebridge.github.io/assets/12555828/843b37b7-c85b-4801-b5e5-d0f3647873b2)

**space between titles**

![Screenshot_2024-04-29-22-24-59-623_com.android.chrome-edit.jpg](https://github.com/activebridge/activebridge.github.io/assets/12555828/d5eb5bfa-63ff-4bfd-87c3-765615614979)

**Comment by Smoke-ck** [comment]
#219

**Comment by Smoke-ck** [comment]
#225
