### ISSUE TITLE
Add missing text

### ISSUE THREAD

**Issue by daryakuritsyna** [activebridge/activebridge.github.io#220]
page About.

Could you add the paragraph "Active Bridge distinguishes itself as a leading application development house, leveraging a compact team of senior and middle Rails developers to deliver technology expertise and object-oriented programming. Our motivated team excels in seamlessly integrating with client operations, driven by a passion for emerging technologies and complex projects."
after the block title "What makes Active Bridge a competitive application development house?".

Now there's duplication of ticket text in the paragraph.

**Comment by Smoke-ck** [comment]
#222

**Comment by Smoke-ck** [comment]
@daryakuritsyna, done
