### ISSUE TITLE
Fix card header on insurance solutions page

### ISSUE THREAD

**Issue by jawny-utah** [activebridge/activebridge.github.io#223]
on this page https://activebridge.org/solutions/insurtech-case
I believe the header on the image should be `Fee schedule calculator`, not Free
<img width="320" alt="image" src="https://github.com/activebridge/activebridge.github.io/assets/59439383/59b2d78b-e180-4f62-905e-d533b00505d7">

per daisyBill app
<img width="551" alt="image" src="https://github.com/activebridge/activebridge.github.io/assets/59439383/8efb5362-b10f-4109-9ba4-e0c8a2757649">

**Comment by Smoke-ck** [comment]
#224

**Comment by Smoke-ck** [comment]
@jawny-utah, done
