### ISSUE TITLE
issues with unminified JavaScript and CSS files

### ISSUE THREAD

**Issue by daryakuritsyna** [activebridge/activebridge.github.io#239]
Semrush has identified 409 instances of unminified JavaScript and CSS files across our website, negatively impacting our domain score and overall page performance. Additionally, Google's PageSpeed Insights reports performance issues on specific pages, such as the "About" page.

**Affected page example**

- **URL:** [https://activebridge.org/about](https://activebridge.org/about)
- **PageSpeed Insights Report:** [View Report](https://pagespeed.web.dev/analysis/https-activebridge-org-about/eprecdcltx?form_factor=mobile)

**Impact**

- **SEO performance:** Unminified files increase page load times, leading to higher bounce rates and lower search engine rankings.
- **User experience:** Slower page loads can result in a suboptimal user experience, potentially decreasing user engagement and conversions.

- **List of affected files:** A detailed list of the unminified files and their respective pages is available in the attached Excel file.

[List of affected files](https://drive.google.com/file/d/1irvrwFNkJo3kuykalSXk81jzq8opfhE3/view?usp=drivesdk)

- **Semrush guidelines:** Refer to Semrush's documentation on unminified files for further insights: [Unminified JavaScript and CSS Files - Semrush](https://www.semrush.com/kb/956-unminified-files)

**Comment by Smoke-ck** [comment]
#240, #241
